apiVersion: apps/v1
kind: Deployment
metadata:
  name: dis-tex-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dis-tex-register
  template:   # pod的信息
    metadata:
      labels:
        app: dis-tex-register
    spec:
      containers:
      - name: dis-tex-register
        image: stephenxjc/dis_tex_register_debug
        volumeMounts:
        - mountPath: /app
          name: host-mount
        - mountPath: /temp
          name: temp
        
      volumes:
      - name: host-mount
        hostPath:
          path: /host
      - name: temp
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dis-tex-register
spec:
  selector:
    app: dis-tex-register
  # type: NodePort
  type: LoadBalancer
  ports:
  - name: dis-tex-register
    port: 50000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dis-tex-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dis-tex-executor
  template:   # pod的信息
    metadata:
      labels:
        app: dis-tex-executor
    spec:
      containers:
      - name: dis-tex-executor
        image: stephenxjc/dis_tex_executor_debug
        resources:
          requests:
            cpu: 1000m
        volumeMounts:
        - mountPath: /app
          name: host-mount
        - mountPath: /temp
          name: temp
        
      volumes:
      - name: host-mount
        hostPath:
          path: /host
      - name: temp
        emptyDir: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dis-tex-executor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dis-tex-executor
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 90